"""add registration column in users

Revision ID: e0eb0941c6a5
Revises: 200222c7de88
Create Date: 2023-03-22 18:19:48.717930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0eb0941c6a5'
down_revision = '200222c7de88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registration_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registration_date')
    # ### end Alembic commands ###
